#!/usr/bin/env python3
import rospy
from da_tangible_tasks.sound_files.sound_effects_master import SoundEffectMaster
import sys

sys.path()
if __name__ == '__main__':
    rospy.init_node('da_tangible_tasks')
    rospy.loginfo('da_tangible_tasks activated!')

    sound_effect_master = SoundEffectMaster()

    if sound_effect_master.mode is not None:
        sound_effect_master.run_sound()