#!/usr/bin/env python3
import rospy
import sys
from da_tangible_tasks.const.sound_consts import SoundEffectConstants

for i in sys.path:
    print(f'{i}')
# sys.path.append('/usr/lib/python3.8/site-packages')
from da_tangible_tasks.sound_files.sound_effects_master import SoundEffectMaster

if __name__ == '__main__':
    rospy.init_node('da_tangible_tasks')
    rospy.loginfo('da_tangible_tasks activated!')

    sound_effect_master = SoundEffectMaster()


    if sound_effect_master.mode is not None:
        # sound_effect_master.run_sound()

        """
        Activate the linde below for speaker test!
        """
        sound_effect_master.speaker_test()