#!/usr/bin/env python3
import rospy
from da_tangible_tasks.activities.sound_effect_master import SoundEffectMaster
from time import sleep

if __name__ == '__main__':
    rospy.init_node('da_tangible_tasks')
    rospy.loginfo('da_tangible_tasks activated!')

    sound_effect_master = SoundEffectMaster()

    """
    Activate the line below for speaker test!
    """
    # sound_effect_master.speaker_test()
    # rospy.loginfo(f'{sound_effect_master.robotline}')

    while True:
        # Always listening to sound_effects topic
        sound_effect_master.get_sound_effect_info()

        if sound_effect_master.mode is not None:
            rospy.loginfo(f"Sound Effect Master "
                          f"mode: {sound_effect_master.mode} "
                          f"random: {sound_effect_master.random} "
                          f"language: {sound_effect_master.language}")
            sound_effect_master.run_sound()
            rospy.loginfo(f'Sound file now playing... :{sound_effect_master.robotline}')
            sleep(10)
